steps:
- name: "gcr.io/cloud-builders/docker"
  entrypoint: 'bash'
  args:
  - -c
  - |
    docker buildx build --no-cache -t gcr.io/ped-dev-308120/emailtest -f Dockerfile . --push
    
# gcloud auth revoke --all
# gcloud auth login
# gcloud config set project ped-dev-308120
# gcloud builds submit --config cloudbuild.api.yaml .
# gcloud run deploy emailtest --image gcr.io/ped-dev-308120/emailtest:latest